import Head from 'next/head'
import { Layout, FixtureRow, FixturesContainer } from '../components'

export function getServerSideProps() {
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Premleague Fixtures App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="my-5">
            <div className="max-w-fit p-3 bg-purple-700 border-transparent rounded-xl">
                <h1 className="font-black">Premier League</h1>
            </div>
        </div>

        <div className="w-full h-16 bg-gray-900 flex justify-center items-center">
        Google Ads
        </div>
            
        <div className="">
            <FixturesContainer>
                <FixtureRow home="Sporting Team" homeIcon="icon" matchDate="DATE" matchTime="TIME" away="Team FC"  awayIcon="icon"/>
            </FixturesContainer>
        </div>
      </Layout>

    </div>
  )
}
